### ISSUE TITLE
상품상세페이지 새로고침시 오류처리

### ISSUE THREAD

**Issue by rlorxl** [Wecloset/pandaFE#31]
1. 상품상세페이지 새로고침시 오류처리
- 새로고침시 전역상태 처리

### Problem
1. userData(리코일에 저장된 상태)가 메인페이지 -> 마켓 -> 마켓디테일 이동시 null이 뜨고, 새로고침시 빈 오브젝트여서 오류가 발생한다.
Q. recoil-persist설치 후 새로고침했을 때 로컬스토리지 데이터를 수동으로 받아와야 하나?

2. 해당페이지 상품데이터가 새로고침시에 날아간다.

**Comment by jiji-hoon96** [comment]
홈화면에서 로그인처리 되는거 손볼려고하는데 겹칠까요? @rlorxl

**Comment by rlorxl** [comment]
어떻게 수정할라구요?

**Comment by jiji-hoon96** [comment]
@rlorxl 소셜이랑 자체회원가입에서 모두 이메일로 날라올수있도록 변경해보게요

**Comment by jiji-hoon96** [comment]
현재 동일한 오류인데 , 
방법 2가지있는거같아요
1. 새로고침 못하게 막기
2. effect 로 페이지전환시에 recoil 재적용

**Comment by rlorxl** [comment]
### Solve

1. userData유지하기
   - atom함수의 effect옵션을 사용하여 상태 변경시 로컬스토리지에 유저데이터를 저장하고 컴포넌트에서 'get'이 감지될 경우 로컬스토리지에 저장된 데이터를 꺼내올 수 있는 로직을 적용. [참고 - 리코일 공식문서](https://recoiljs.org/ko/docs/guides/testing#%EC%BB%A4%EC%8A%A4%ED%85%80-%ED%9B%85-%EB%82%B4%EB%B6%80%EC%97%90%EC%84%9C-recoil-%EC%83%81%ED%83%9C-%ED%85%8C%EC%8A%A4%ED%8A%B8%ED%95%98%EA%B8%B0)

2. 상세페이지 데이터 유지
   - useQuery의 enabled 옵션추가.
