### ISSUE TITLE
프로필페이지 수정

### ISSUE THREAD

**Issue by rlorxl** [Wecloset/pandaFE#49]
### 프로필 페이지 수정사항

1. 닉네임
   - [x]  변경버튼 눌렀을 때 인풋에 커서가 오도록 수정
   - [x] #59
   - [x] 현재 변경 누르고 인풋에 아무 입력없이 그냥 완료 누르면 변화가 없음. 요청보내게 수정.

2. 키워드
   - [x] 키워드 선택시 뒤쪽배경 컬러 black, opacity-50으로 수정.
   - [x] 변경창에서 x버튼 눌렀을 때는 변경하던것 취소하도록 수정. 하단 완료버튼 눌렀을 때 요청이 가도록. (변경버튼X) 
   - [x] 키워드 변경과정에서는 인풋에 보여지는게 변경되지 않게 수정.

3. 프로필이미지
   - [x] 프로필이미지 변경 추가

**Comment by jiji-hoon96** [comment]
@rlorxl 감사합니다 :)
