### ISSUE TITLE
로그아웃 에러

### ISSUE THREAD

**Issue by rlorxl** [Wecloset/pandaFE#71]
로그아웃 버튼 클릭했을 때 세션 삭제가 안됨

**Comment by jiji-hoon96** [comment]
@rlorxl 이거는 로그아웃 버튼을 눌럿을때 거의 대부분 세션삭제되면서 로그아웃된 후에 home 으로 처리가 되는데
간혹 세션삭제가 안되는 경우가발견되어서 
퇴근하고나서 다시 확인해보겠습니다

**Comment by rlorxl** [comment]
도라버려ㅠㅠ
