### ISSUE TITLE
세부 수정사항

### ISSUE THREAD

**Issue by jiji-hoon96** [Wecloset/pandaFE#76]
- [x] 검색창 input.trim() === "" 이면 return (캐시 저장X, 검색X)
- [x] 최근검색어 10개만 노출시키기

**Comment by rlorxl** [comment]
### 추가 이슈

![Image](https://user-images.githubusercontent.com/90922593/230346746-966e3e06-0742-46d8-bbd0-958ce9e15e63.png)

1. 오류해결해주세요!
- 최근검색어 똑같은 키워드 중복저장 안되게
![Image](https://user-images.githubusercontent.com/90922593/230347071-d95ff3f9-e781-4fec-baac-059c3894b90f.png)

2. 최근검색어 키워드 클릭시 검색이 되도록
3. search상단 뒤로가기 버튼 눌렀을 때 항상 /search 페이지로 이동되도록
(지금은 이전에 검색했던 화면으로 되돌아감)
4. 검색페이지 '검색 결과가 없습니다' 코멘트가 계속 떠있는데 submit안보냈을때는 안뜨게 수정!

@jiji-hoon96

**Comment by jiji-hoon96** [comment]
2번 키워드클릭이랑 4번 submit 안되면 값 뜨게 수정진행중

**Comment by jiji-hoon96** [comment]
4번 진행중

**Comment by jiji-hoon96** [comment]
#84 pr 올림
